feat: add alternative builders and build options from command line

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,3 +1,15 @@
 #!/bin/bash
 
-docker build --pull -t docker-wine .
+BUILD_ARGS=("$@")
+BUILD_CMD="docker build"
+
+if ! docker -v >/dev/null 2>&1; then
+    if buildah -v >/dev/null 2>&1; then
+        BUILD_CMD="buildah bud"
+    else
+        echo "ERROR: Docker is not running or not installed, unable to proceed"
+        exit 1
+    fi
+fi
+
+${BUILD_CMD} "${BUILD_ARGS[@]}" -t docker-wine .
