feat: add rdp capability

diff --git a/docker-wine b/docker-wine
--- a/docker-wine
+++ b/docker-wine
@@ -1,47 +1,5 @@
 #!/bin/bash
 
-# Run docker with just X11 support
-docker_run () {
-    docker run -it \
-    --rm \
-    --env="DISPLAY" \
-    --volume="${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro" \
-    --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro" \
-    --volume="/etc/localtime:/etc/localtime:ro" \
-    --volume="winehome:/home/wineuser" \
-    --hostname="$(hostname)" \
-    --name="wine" \
-    "${DOCKER_IMAGE}" "$@"
-}
-
-
-# Run docker with X11 and audio support
-docker_run_with_audio () {
-    docker run -it \
-    --rm \
-    --env="DISPLAY" \
-    --volume="${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro" \
-    --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro" \
-    --volume="/tmp/pulse-socket:/tmp/pulse-socket" \
-    --volume="/etc/localtime:/etc/localtime:ro" \
-    --volume="winehome:/home/wineuser" \
-    --hostname="$(hostname)" \
-    --name="wine" \
-    "${DOCKER_IMAGE}" "$@"
-}
-
-
-# Run docker on macOS with X11 over TCP socket
-docker_run_on_mac () {
-    docker run -it \
-    --rm \
-    --env="DISPLAY=host.docker.internal:0" \
-    --volume="winehome:/home/wineuser" \
-    --hostname="$(hostname)" \
-    --name="wine" \
-    "${DOCKER_IMAGE}" "$@"
-}
-
 print_help () {
     echo "Usage: $0 [OPTION]... [COMMAND [ARGS]...]..."
     echo
@@ -93,33 +51,18 @@ print_help () {
 add_run_arg () {
     local arg="$1"
 
-    if [ -z "${RUN_ARGS}" ]; then
-        RUN_ARGS+="${arg}"
-    else
-        RUN_ARGS+=" ${arg}"
-    fi
-}
-
-docker_run () {
-    local run_mode="$1"
-    local run_args="$2"
-    local image="$3"
-    local cmd_args="$4"
-
-    docker run $run_mode $run_args $image $cmd_args
+    RUN_ARGS+=("${arg}")
 }
 
 
-DOCKER_IMAGE="${scottyhardy/docker-wine:latest}"
-LOCAL_IMAGE="${docker-wine:latest}"
+# Set default values
+DOCKER_IMAGE="scottyhardy/docker-wine:latest"
+LOCAL_IMAGE="docker-wine:latest"
 USE_LOCAL_IMAGE="no"
 RDP_SERVER="no"
-RUN_MODE="-it"
-RUN_ARGS=""
-
-USER="wineuser"
+RUN_ARGS=()
+USER_HOME="/home/wineuser"
 USER_VOLUME="winehome"
-USER_PASSWD=""
 
 while [ $# -gt 0 ]; do
   case "$1" in
@@ -127,22 +70,25 @@ while [ $# -gt 0 ]; do
         USE_LOCAL_IMAGE="yes"
         ;;
     --run-as-root)
-        RUN_AS="root"
+        add_run_arg --env="RUN_AS_ROOT=yes"
         ;;
     --run-as-me)
-        RUN_AS="me"
+        add_run_arg --env="USER_NAME=$(whoami)"
+        add_run_arg --env="USER_UID=$(id -u)"
+        add_run_arg --env="USER_GID=$(id -g)"
         ;;
     --rdp=*)
-        RDP_SERVER="$1#*="
+        RDP_SERVER="${1#*=}"
         ;;
     --user-home=*)
-        USER_HOME="$1#*="
+        USER_HOME="${1#*=}"
+        add_run_arg --env="USER_HOME=${USER_HOME}"
         ;;
     --user-passwd=*)
-        USER_PASSWD="$1#*="
+        add_run_arg --env="USER_PASSWD=${1#*=}"
         ;;
     --volume=*)
-        add_run_option "$1"
+        add_run_arg "$1"
         ;;
     --help)
         print_help
@@ -161,20 +107,24 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-CMD_ARGS="$@"
+# Collect remaining command line args to pass to the container to run
+CMD_ARGS=("$@")
 
-# Sanity check
+# Sanity checks
 if ! docker -v >/dev/null 2>&1; then
     echo "ERROR: Docker is not running or not installed, unable to proceed"
     exit 1
 fi
 
-# Process RDP_SERVER value
-if ! echo "${RDP_SERVER}" | grep -i -E '^(no|start|stop|restart|interactive)$'; then
+if ! echo "${RDP_SERVER}" | grep -E '^(no|start|stop|restart|interactive)$'; then
     echo "ERROR: '${RDP_SERVER}' is not a valid value for --rdp option"
     exit 1
 fi
 
+if [ "${RDP_SERVER}" != "no" ] && [ -n "${CMD_ARGS[0]}" ]; then
+    echo "ERROR: Commands cannot be passed to container when using --rdp option"
+    exit 1
+fi
 
 # Grab the latest image from docker hub or use the locally built version
 if [ "${USE_LOCAL_IMAGE}" == "no" ]; then
@@ -183,70 +133,117 @@ else
     DOCKER_IMAGE="${LOCAL_IMAGE}"
 fi
 
-# Create the docker volume to store user's home
-if ! docker volume ls -qf "name=winehome" | grep -q "^winehome$"; then
+# Create the docker volume to store user's home only if using default winehome
+if [ "${USER_VOLUME}" == "winehome" ] && ! docker volume ls -qf "name=winehome" | grep -q "^winehome$"; then
     echo "INFO: Creating Docker volume container 'winehome'..."
     docker volume create winehome
-else
-    echo "INFO: Using existing Docker volume container 'winehome'..."
 fi
 
-# Check if running on a Mac
-if [ "$(uname)" == "Darwin" ]; then
-    # Check XQuartz installed
-    if ! command -v xquartz >/dev/null 2>&1; then
-        echo "ERROR: XQuartz does not appear to be installed"
-        exit 1
-    fi
+# Add common docker run args
+add_run_arg --rm
+add_run_arg --hostname="$(hostname)"
+add_run_arg --name="wine"
+add_run_arg --volume="${USER_VOLUME}:${USER_HOME}"
 
-    # Configure XQuartz if required
-    if [ "$(defaults read org.macosforge.xquartz.X11 app_to_run)" != "/usr/bin/true" ]; then
-        defaults write org.macosforge.xquartz.X11 app_to_run /usr/bin/true
-    fi
+# Run in RDP mode
+if [ "${RDP_SERVER}" != "no" ]; then
 
-    if [ "$(defaults read org.macosforge.xquartz.X11 nolisten_tcp)" != "0" ]; then
-        defaults write org.macosforge.xquartz.X11 nolisten_tcp 0
-    fi
+    case "${RDP_SERVER}" in
+        interactive)
+            docker_run -it "${RUN_ARGS[@]}" "${DOCKER_IMAGE}" /bin/bash
+            ;;
+        start)
+            docker_run --detach "${RUN_ARGS[@]}" "${DOCKER_IMAGE}"
+            ;;
+        stop)
+            docker kill wine
+            exit $?
+            ;;
+        restart)
+            docker kill wine
+            docker_run --detach "${RUN_ARGS[@]}" "${DOCKER_IMAGE}"
+            ;;
+        *)
+            echo "ERROR: '${RDP_SERVER}' is not a valid value for --rdp option"
+            exit 1
+            ;;
+    esac
 
-    # Allow localhost to access XQuartz if required
-    if ! xhost | grep "INET:localhost" >/dev/null 2>&1; then
-        echo "WARNING: Adding localhost to authorized xhost clients"
-        xhost + 127.0.0.1
-    fi
-
-    docker_run_on_mac "$@"
+# Run in X11 forwarding mode
 else
-    # Check for .Xauthority command -v is required for authenticating as the current user on the host's X11 server
-    if [ -z "${XAUTHORITY}" ] && [ -s "${HOME}/.Xauthority" ]; then
-        echo "ERROR: No valid .Xauthority file found for X11"
-        exit 1
-    fi
 
-    # Use audio if PulseAudio is installed
-    if command -v pulseaudio >/dev/null 2>&1; then
-        # One-off setup for creation of UNIX socket for PulseAudio to allow access for other users
-        if [ ! -f "${HOME}/.config/pulse/default.pa" ]; then
-            echo "INFO: Creating PulseAudio config file ${HOME}/.config/pulse/default.pa"
-            mkdir -p "${HOME}/.config/pulse"
-            echo -e ".include /etc/pulse/default.pa\nload-module module-native-protocol-unix auth-anonymous=1 socket=/tmp/pulse-socket" > "${HOME}/.config/pulse/default.pa"
+    # Run in X11 forwarding mode on macOS
+    if [ "$(uname)" == "Darwin" ]; then
+
+        # Check XQuartz installed
+        if ! command -v xquartz >/dev/null 2>&1; then
+            echo "ERROR: XQuartz does not appear to be installed"
+            exit 1
         fi
 
-        if [ ! -e "/tmp/pulse-socket" ]; then
-            # Restart PulseAudio daemon to ensure the UNIX socket is created
-            echo "INFO: No socket found for PulseAudio so restarting service..."
-            pulseaudio -k
-            pulseaudio --start
-            sleep 1
+        # Configure XQuartz
+        if [ "$(defaults read org.macosforge.xquartz.X11 app_to_run)" != "/usr/bin/true" ]; then
+            defaults write org.macosforge.xquartz.X11 app_to_run /usr/bin/true
         fi
 
-        if [ -e "/tmp/pulse-socket" ]; then
-            docker_run_with_audio "$@"
+        if [ "$(defaults read org.macosforge.xquartz.X11 nolisten_tcp)" != "0" ]; then
+            defaults write org.macosforge.xquartz.X11 nolisten_tcp 0
+        fi
+
+        # Allow localhost to access XQuartz
+        if ! xhost | grep "INET:localhost" >/dev/null 2>&1; then
+            echo "WARNING: Adding localhost to authorized xhost clients"
+            xhost + 127.0.0.1
+        fi
+
+        add_run_arg --env="DISPLAY=host.docker.internal:0"
+        docker_run -it "${RUN_ARGS[@]}" "${DOCKER_IMAGE}" "${CMD_ARGS[@]}"
+
+    # Run in X11 forwarding mode on Linux
+    elif [ "$(uname)" == "Linux" ]; then
+
+        # Check for .Xauthority command -v is required for authenticating as the current user on the host's X11 server
+        if [ -z "${XAUTHORITY}" ] && [ -s "${HOME}/.Xauthority" ]; then
+            echo "ERROR: No valid .Xauthority file found for X11"
+            exit 1
+        fi
+
+        # Use audio if pulseaudio is installed
+        if command -v pulseaudio >/dev/null 2>&1; then
+            # One-off setup for creation of UNIX socket for pulseaudio to allow access for other users
+            if [ ! -f "${HOME}/.config/pulse/default.pa" ]; then
+                echo "INFO: Creating pulseaudio config file ${HOME}/.config/pulse/default.pa"
+                mkdir -p "${HOME}/.config/pulse"
+                echo -e ".include /etc/pulse/default.pa\nload-module module-native-protocol-unix auth-anonymous=1 socket=/tmp/pulse-socket" > "${HOME}/.config/pulse/default.pa"
+            fi
+
+            if [ ! -e "/tmp/pulse-socket" ]; then
+                # Restart pulseaudio daemon to ensure the UNIX socket is created
+                echo "INFO: No socket found for pulseaudio so restarting service..."
+                pulseaudio -k
+                pulseaudio --start
+                sleep 1
+            fi
+
+            # Add the pulseaudio UNIX socket
+            if [ -e "/tmp/pulse-socket" ]; then
+                add_run_arg --volume="/tmp/pulse-socket:/tmp/pulse-socket"
+            else
+                echo "INFO: pulseaudio socket /tmp/pulse-socket doesn't exist, so sound will not function"
+            fi
         else
-            echo "INFO: PulseAudio socket /tmp/pulse-socket doesn't exist, so sound will not function"
-            docker_run "$@"
+            echo "INFO: pulseaudio not installed so running without sound"
         fi
+
+        # Add common Linux docker run args
+        add_run_arg --env="DISPLAY"
+        add_run_arg --volume="${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro"
+        add_run_arg --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro"
+        add_run_arg --volume="/etc/localtime:/etc/localtime:ro"
+
+        docker_run -it "${RUN_ARGS[@]}" "${DOCKER_IMAGE}" "${CMD_ARGS[@]}"
     else
-        echo "INFO: PulseAudio not installed so running without sound"
-        docker_run "$@"
+        echo "ERROR: Unknown operating system '$(uname)'"
+        exit 1
     fi
 fi
