Wait for Docker and XQuartz

diff --git a/docker-wine b/docker-wine
--- a/docker-wine
+++ b/docker-wine
@@ -675,8 +675,28 @@ CMD_ARGS=("$@")
 
 # Sanity checks
 if ! docker system info >/dev/null 2>&1; then
-    echo "ERROR: Docker is not running or not installed, unable to proceed"
-    exit 1
+    if [ "$(uname)" == "Darwin" ]; then
+        if open -a Docker.app; then
+            #echo "⏳ Waiting for Docker to initialize... (timeout: 15s)"
+            timeout=15
+            elapsed=0
+
+            while ! docker-compose ls > /dev/null 2>&1; do
+                sleep 1
+                ((elapsed++))
+                if [ "$elapsed" -ge "$timeout" ]; then
+                    echo "❌ Timeout waiting for Docker to start."
+                    exit 1
+                fi
+            done
+        else
+            echo "ERROR: Docker is not running or not installed, unable to proceed"
+            exit 1
+        fi
+    else
+        echo "ERROR: Docker is not running or not installed, unable to proceed"
+        exit 1
+    fi
 fi
 
 if ! echo "${USE_RDP_SERVER}" | grep -q -E "^(no|start|stop|restart|interactive)$"; then
@@ -751,9 +771,8 @@ else
             open -a xquartz
 
             # Wait for X11 socket to appear (timeout: 15s)
-            SOCKET="/tmp/.X11-unix/X0"
             for i in {1..15}; do
-                if [ -S "$SOCKET" ]; then
+                if DISPLAY=:0 xdpyinfo >/dev/null 2>&1; then
                     #echo "✅ X11 socket is now available."
                     break
                 fi
@@ -761,7 +780,7 @@ else
                 sleep 1
             done
 
-            if [ ! -S "$SOCKET" ]; then
+            if DISPLAY=:0 xdpyinfo >/dev/null 2>&1; then
                 echo "❌ Timeout: X11 socket still not available."
                 exit 1
             fi
