feat: add image wine branch and version tags to github build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,6 +10,10 @@ on:
 jobs:
   docker:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        wine_branch:
+          - stable
     steps:
       -
         name: Checkout
@@ -37,12 +41,28 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       -
+        name: Extract wine version
+        env:
+          WINE_BRANCH: ${{ matrix.wine_branch }}
+        run: |
+          WINE_VER="$(docker run -it --rm "${DOCKER_REPO}" /bin/bash -c "dpkg -s wine-${WINE_BRANCH} \
+          | grep '^Version:\s' | awk '{print \$2}' | sed -E 's/~.*$//'" | tr -d "\r")"
+          if echo "${WINE_VER}" | grep -q -E "^[0-9]+(\.[0-9]+)*$"; then
+              echo "Found wine version '${WINE_VER}'"
+              echo "WINE_VER=${WINE_VER}" >> $GITHUB_ENV
+          else
+              echo "ERROR: Unable to determine wine version"
+              exit 1
+          fi
+      -
         name: Build and push
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           push: true
-          tags: scottyhardy/docker-wine:latest
+          tags: scottyhardy/docker-wine:latest,
+            scottyhardy/docker-wine:${{ matrix.wine_branch }},
+            scottyhardy/docker-wine:${{ matrix.wine_branch }}-${{ env.WINE_VER }}
       -
         name: Update repo description
         uses: peter-evans/dockerhub-description@v2
