feat: add wine version extraction to github test workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,6 +8,10 @@ on:
 jobs:
   docker:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        wine_branch:
+          - stable
     steps:
       -
         name: Checkout
@@ -24,6 +28,20 @@ jobs:
         with:
           load: true
           tags: docker-wine:latest
+      -
+        name: Extract wine version
+        env:
+          WINE_BRANCH: ${{ matrix.wine_branch }}
+        run: |
+          WINE_VER="$(docker run --rm docker-wine /bin/bash -c "dpkg -s wine-${WINE_BRANCH} \
+          | grep '^Version:\s' | awk '{print \$2}' | sed -E 's/~.*$//'" | tr -d "\r")"
+          if echo "${WINE_VER}" | grep -q -E "^[0-9]+(\.[0-9]+)*$"; then
+              echo "Found wine version '${WINE_VER}'"
+              echo "WINE_VER=${WINE_VER}" >> $GITHUB_ENV
+          else
+              echo "ERROR: Unable to determine wine version"
+              exit 1
+          fi
       -
         name: Test
         run: |
